

## LABELS IN PROJECT

WALKING = 1
WALKING_UPSTAIRS = 2
WALKING_DOWNSTAIRS = 3
SITTING = 4
STANDING = 5
LAYING = 6
STAND_TO_SIT = 7
SIT_TO_STAND = 8
SIT_TO_LIE = 9
LIE_TO_SIT = 10
STAND_TO_LIE = 11
LIE_TO_STAND = 12
RUNNING = 13



DATAFOLDER = 'data/'
HAPT_DATASET_FOLDER = DATAFOLDER +' hapt_dataset/'
PROJECT_DATASET = DATAFOLDER + 'project_dataset/'
EXPERIMENTS_RAWDATA = DATAFOLDER +'expriments_rawdata/'
EXPERIMENTS_CLEANED_DATA = DATAFOLDER +'expriments_cleaned_dataset/'
OUTPUT_DATA = DATAFOLDER + 'output_data/'


##  FILENAMES

MODEL_BEST_WEIGHTS_PATH ='model_best_weights.h5'
MODEL_SUMMARY_PATH = 'modelsummary.txt'
MODEL_LOG_PATH = 'training.log'
MODEL_JSON_PATH ='model.json'
MODEL_WEIGHTS_PATH ='model_weights.h5'
MODEL_PATH ='model.h5'


BASIC_DATASET = PROJECT_DATASET+'dataset.csv'
FEATURED_DATASET = PROJECT_DATASET + 'featured_dataset.csv'
